services:
  app:
    entrypoint:
    - sleep
    - infinity
    build:
      context: ./devenv
      dockerfile: ./devenv/Dockerfile
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

