services:
  app:
    entrypoint:
    - sleep
    - infinity
    build:
      context: ./devenv
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

